package co.edu.uniajc.model;

// Generated 10/03/2015 11:21:36 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * Consignaciones generated by hbm2java
 */
public class Consignaciones implements java.io.Serializable {

	private ConsignacionesId id;
	private Cuentas cuentas;
	private Usuarios usuarios;
	private BigDecimal conValor;
	private Date conFecha;
	private String conDescripcion;

	public Consignaciones() {
	}

	public Consignaciones(ConsignacionesId id, Cuentas cuentas,
			BigDecimal conValor, Date conFecha, String conDescripcion) {
		this.id = id;
		this.cuentas = cuentas;
		this.conValor = conValor;
		this.conFecha = conFecha;
		this.conDescripcion = conDescripcion;
	}

	public Consignaciones(ConsignacionesId id, Cuentas cuentas,
			Usuarios usuarios, BigDecimal conValor, Date conFecha,
			String conDescripcion) {
		this.id = id;
		this.cuentas = cuentas;
		this.usuarios = usuarios;
		this.conValor = conValor;
		this.conFecha = conFecha;
		this.conDescripcion = conDescripcion;
	}

	public ConsignacionesId getId() {
		return this.id;
	}

	public void setId(ConsignacionesId id) {
		this.id = id;
	}

	public Cuentas getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Cuentas cuentas) {
		this.cuentas = cuentas;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public BigDecimal getConValor() {
		return this.conValor;
	}

	public void setConValor(BigDecimal conValor) {
		this.conValor = conValor;
	}

	public Date getConFecha() {
		return this.conFecha;
	}

	public void setConFecha(Date conFecha) {
		this.conFecha = conFecha;
	}

	public String getConDescripcion() {
		return this.conDescripcion;
	}

	public void setConDescripcion(String conDescripcion) {
		this.conDescripcion = conDescripcion;
	}

}
