package co.edu.uniajc.model;

// Generated 10/03/2015 11:21:36 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * TiposDocumentos generated by hbm2java
 */
public class TiposDocumentos implements java.io.Serializable {

	private long tdocCodigo;
	private String tdocNombre;
	private Set<Clientes> clienteses = new HashSet<Clientes>(0);

	public TiposDocumentos() {
	}

	public TiposDocumentos(long tdocCodigo, String tdocNombre) {
		this.tdocCodigo = tdocCodigo;
		this.tdocNombre = tdocNombre;
	}

	public TiposDocumentos(long tdocCodigo, String tdocNombre, Set clienteses) {
		this.tdocCodigo = tdocCodigo;
		this.tdocNombre = tdocNombre;
		this.clienteses = clienteses;
	}

	public long getTdocCodigo() {
		return this.tdocCodigo;
	}

	public void setTdocCodigo(long tdocCodigo) {
		this.tdocCodigo = tdocCodigo;
	}

	public String getTdocNombre() {
		return this.tdocNombre;
	}

	public void setTdocNombre(String tdocNombre) {
		this.tdocNombre = tdocNombre;
	}

	public Set getClienteses() {
		return this.clienteses;
	}

	public void setClienteses(Set clienteses) {
		this.clienteses = clienteses;
	}

}
